1911-grace-shopper/grace-shopper

package.json
server/db/models/user.js

test: changed the project name

---

.travis.yml
package-lock.json

boilermaker review

---

server/db/models/index.js
server/db/models/order.js
server/db/models/product.js
server/db/models/user.js

Models and Assosiations Initial Set Up

---

server/api/index.js
server/api/products.js

all products route added

---

script/seed.js

updated the seed file

---

client/store/product.js

product reducer created

---

client/components/allProducts.js
client/routes.js
client/store/index.js

all product view is working

---

client/app.js
client/components/cart.js
client/components/index.js
client/components/navbar.js
client/routes.js
server/index.js

---
added cart link in navbar and added cart system with dummy data

added link in navbar and cart system with dummy data

---

client/components/singleProductView.js
client/routes.js
client/store/product.js
server/api/products.js

Single view #12

---

client/components/allProducts.js
client/components/singleProductView.js
client/store/productReducer.js

Bug: single page link fixed

---

client/components/singleProductView.js

added curly brace

---

client/components/singleProductView.js
client/store/cart.js
server/index.js

add item to sessionStorage success

---

script/seed.js
server/api/products.js
server/db/models/index.js
server/db/models/order.js
server/db/models/orderDetails.js
server/db/models/product.js

Edit: updated orderDetail table

---

client/components/cart.js
client/components/singleProductView.js
client/store/cart.js
client/store/index.js
public/index.html
public/style.css

Cart store

---

client/components/cart.js
client/store/cart.js

quantity shows in cart

---

client/components/cart.js
client/components/checkout.js
client/routes.js
server/api/checkout.js
server/api/index.js
server/db/models/order.js

Checkout component

---

client/components/confirmation.js
server/db/models/order.js
server/db/models/orderDetails.js

edited order and orderDetails db

---

client/components/singleProductView.js
client/store/cart.js
server/api/cartRoutes.js
server/api/checkout.js
server/api/index.js

can create a new pending order for cart

---

client/components/checkout.js
client/components/checkoutForm.js
client/components/confirmation.js
client/routes.js

Confirmation component

---

client/store/cart.js
server/api/cartRoutes.js

updating through table

---

client/store/cart.js

quantity add successfull

---

client/store/user.js

bugfix: login route fixed

---

client/components/cart.js
client/components/checkout.js
client/components/checkoutForm.js
client/components/confirmation.js
client/store/cart.js
client/store/checkoutReducer.js

Final checkout

---

client/store/cart.js
server/api/cartRoutes.js
server/api/checkout.js
server/index.js

adding res.send to cartRoutes

---

client/store/cart.js
client/store/user.js
server/api/cartRoutes.js
server/api/checkout.js

Cart updates

---

client/components/checkout.js
client/components/checkoutForm.js

bugfix: checkout userid error fixed and warning message restored

---

client/components/checkout.js
client/components/navbar.js
client/components/singleProduct.js
client/store/checkoutReducer.js
public/index.html
script/seed.js
server/images/index.js

bugfix: checkout form with new feature with badge icon

---

client/components/cart.spec.js
client/store/product.spec.js

Added Product Reducer test specs
